@extends('layouts.dashboard', ['role' => $role, 'dashboardRoute' => $dashboardRoute])

@section('title', 'Detail Pemesanan')

@section('content')
    <div class="mb-4"><a href="{{ route('ppat.orders.index') }}" class="small text-primary"><i class="fas fa-arrow-left mr-1"></i>Kembali ke pemesanan</a><div class="d-flex flex-wrap align-items-center justify-content-between mt-2"><div><h1 class="h3 mb-1 text-gray-800">{{ $order->title }}</h1><p class="mb-0 text-gray-600">Dibuat {{ $order->created_at->format('d/m/Y H:i') }} oleh {{ $order->creator->name }}</p></div><form method="POST" action="{{ route('ppat.orders.status.update', $order) }}" class="d-flex align-items-center mt-2 mt-md-0">@csrf @method('PATCH')<label for="order-status" class="sr-only">Status pemesanan</label><select id="order-status" name="status" class="form-control form-control-sm mr-2">@foreach ($statuses as $status)<option value="{{ $status }}" @selected($order->status === $status)>{{ $status }}</option>@endforeach</select><button class="btn btn-sm btn-primary" type="submit"><i class="fas fa-save mr-1"></i>Simpan</button></form></div></div>
    @if (session('success'))<div class="alert alert-success alert-dismissible fade show" role="alert">{{ session('success') }}<button type="button" class="close" data-dismiss="alert" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div>@endif
    @if ($errors->has('status'))<div class="alert alert-danger" role="alert">{{ $errors->first('status') }}</div>@endif

    <div class="row">
        <div class="col-lg-6 mb-4"><section class="bg-white border rounded shadow-sm p-4 h-100"><h2 class="h5 font-weight-bold mb-3">Client / Pemohon</h2><dl class="row mb-0"><dt class="col-sm-4">Nama</dt><dd class="col-sm-8">{{ $order->client_name_snapshot }}</dd><dt class="col-sm-4">Tipe</dt><dd class="col-sm-8">{{ ['perorangan' => 'Perorangan', 'individu' => 'Individu', 'badan_usaha' => 'Badan usaha / badan hukum', 'lembaga_non_ahu' => 'Lembaga / badan / perkumpulan non AHU', 'kuasa' => 'Kuasa'][$order->client_type_snapshot] ?? $order->client_type_snapshot }}</dd>@if ($order->represented_party_snapshot)<dt class="col-sm-4">Mewakili</dt><dd class="col-sm-8">{{ $order->represented_party_snapshot }}</dd>@endif<dt class="col-sm-4">Identitas</dt><dd class="col-sm-8">{{ $order->client_nik_snapshot ?: '-' }}</dd><dt class="col-sm-4">WhatsApp</dt><dd class="col-sm-8">{{ $order->client_phone_snapshot }}</dd><dt class="col-sm-4">Email</dt><dd class="col-sm-8">{{ $order->client_email_snapshot ?: '-' }}</dd><dt class="col-sm-4">Alamat</dt><dd class="col-sm-8">{!! nl2br(e($order->client_address_snapshot)) !!}</dd></dl></section></div>
        <div class="col-lg-6 mb-4"><section class="bg-white border rounded shadow-sm p-4 h-100"><h2 class="h5 font-weight-bold mb-3">Detail Pekerjaan</h2><dl class="row mb-0"><dt class="col-sm-4">Layanan</dt><dd class="col-sm-8">{{ $order->service_name_snapshot }} @if ($order->service_code_snapshot)<span class="text-muted">({{ $order->service_code_snapshot }})</span>@endif</dd><dt class="col-sm-4">Ringkasan</dt><dd class="col-sm-8">{!! $order->description ? nl2br(e($order->description)) : '-' !!}</dd><dt class="col-sm-4">Objek / lokasi</dt><dd class="col-sm-8">{!! $order->object_location ? nl2br(e($order->object_location)) : '-' !!}</dd><dt class="col-sm-4">Pihak terkait</dt><dd class="col-sm-8">{!! $order->related_parties ? nl2br(e($order->related_parties)) : '-' !!}</dd><dt class="col-sm-4">Catatan internal</dt><dd class="col-sm-8">{!! $order->internal_notes ? nl2br(e($order->internal_notes)) : '-' !!}</dd></dl></section></div>
    </div>

    <section class="bg-white border rounded shadow-sm"><div class="p-4 border-bottom"><h2 class="h5 font-weight-bold mb-0">Berkas Pendukung</h2></div>@forelse ($order->files as $file)@php($isPdf = strtolower(pathinfo($file->original_name, PATHINFO_EXTENSION)) === 'pdf')<div class="d-flex flex-wrap align-items-center justify-content-between p-3 border-bottom"><div class="mr-3 mb-2 mb-sm-0"><div class="font-weight-bold">{{ $file->label }}</div><div class="small text-muted">{{ $file->original_name }} · {{ number_format($file->size / 1024, 0) }} KB</div></div><a class="btn btn-sm btn-outline-primary" href="{{ route('ppat.orders.files.preview', $file) }}" target="_blank" rel="noopener"><i class="fas {{ $isPdf ? 'fa-file-pdf' : 'fa-file-word' }} mr-1"></i>{{ $isPdf ? 'Lihat PDF' : 'Unduh Word' }}</a></div>@empty<p class="text-muted p-4 mb-0">Belum ada berkas pendukung.</p>@endforelse</section>
@endsection
